import { ReviewExecutionSchema, ReviewTargetBindingSchema, ReviewTargetSchema, MemoryScheduleStateSchema, ReviewEventSchemaV2, SchedulerConfigurationSchema, type ReviewExecution, type ReviewTarget, type ReviewTargetBinding, type MemoryScheduleState, type SuccessorReviewEvent, type SchedulerConfiguration } from '@hy3-clinic/shared';
import type { SqliteDb } from '../db/database.js';
const json = (v: unknown) => JSON.stringify(v);
const parseJson = (v: string) => JSON.parse(v) as Record<string, unknown>;
export function createReviewSuccessorRepo(db: SqliteDb) {
  const target = (id: string) => { const r = db.prepare('SELECT * FROM review_targets WHERE id=?').get(id) as any; return r ? ReviewTargetSchema.parse({id:r.id,workspaceId:r.workspace_id,courseId:r.course_id,targetKind:r.target_kind,originEvidenceId:r.origin_evidence_id,currentBindingVersion:r.current_binding_version,status:r.status,createdAt:r.created_at,updatedAt:r.updated_at}) : undefined; };
  const binding = (id: string, version: number) => { const r = db.prepare('SELECT * FROM review_target_bindings WHERE review_target_id=? AND binding_version=?').get(id,version) as any; return r ? ReviewTargetBindingSchema.parse({reviewTargetId:r.review_target_id,bindingVersion:r.binding_version,contractVersionId:r.contract_version_id,curriculumVersionId:r.curriculum_version_id,learningUnitId:r.learning_unit_id,objectiveId:r.objective_id,executionSourceManifestFingerprint:r.execution_source_manifest_fingerprint,validFrom:r.valid_from,validTo:r.valid_to,createdAt:r.created_at}) : undefined; };
  const state = (id: string) => { const r = db.prepare('SELECT * FROM memory_schedule_states WHERE review_target_id=?').get(id) as any; return r ? MemoryScheduleStateSchema.parse({reviewTargetId:r.review_target_id,policyVersion:r.policy_version,lifecycleState:r.lifecycle_state,dueAt:r.due_at,lastReviewedAt:r.last_reviewed_at,stability:r.stability,difficulty:r.difficulty,scheduledDays:r.scheduled_days,repetitions:r.repetitions,lapses:r.lapses,lastReviewEventId:r.last_review_event_id,rowVersion:r.row_version,createdAt:r.created_at,updatedAt:r.updated_at}) : undefined; };
  const event = (id: string) => { const r = db.prepare('SELECT * FROM successor_review_events WHERE id=?').get(id) as any; return r ? ReviewEventSchemaV2.parse({id:r.id,reviewTargetId:r.review_target_id,bindingVersion:r.binding_version,policyVersion:r.policy_version,kind:r.kind,sourceOutcomeId:r.source_outcome_id,reviewExecutionId:r.review_execution_id,rating:r.rating,occurredAt:r.occurred_at,recordedAt:r.recorded_at,preState:parseJson(r.pre_state),postState:parseJson(r.post_state),exactInputTime:r.exact_input_time,dueAt:r.due_at,idempotencyKey:r.idempotency_key}) : undefined; };
  const execution = (id: string) => { const r = db.prepare('SELECT * FROM review_executions WHERE id=?').get(id) as any; return r ? ReviewExecutionSchema.parse({id:r.id,reviewTargetId:r.review_target_id,bindingVersion:r.binding_version,consumedRowVersion:r.consumed_row_version,workspaceId:r.workspace_id,courseId:r.course_id,agendaId:r.agenda_id,assessmentVersionId:r.assessment_version_id,attemptId:r.attempt_id,status:r.status,failureReason:r.failure_reason,createdAt:r.created_at,updatedAt:r.updated_at}) : undefined; };
  return {
    ensureConfiguration(config: SchedulerConfiguration) { const c=SchedulerConfigurationSchema.parse(config); db.prepare(`INSERT OR IGNORE INTO review_scheduler_configurations(version,algorithm_generation,package_name,package_version,local_adapter_version,rating_policy_version,requested_retention,config_hash,fuzz,short_term,maximum_due_horizon_days,effective_at,retired_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(c.version,c.algorithmGeneration,c.packageName,c.packageVersion,c.localAdapterVersion,c.ratingPolicyVersion,c.requestedRetention,c.configHash,0,0,c.maximumDueHorizonDays,c.effectiveAt,c.retiredAt); },
    getTarget: target,
    listTargets(workspaceId: string) { return (db.prepare('SELECT id FROM review_targets WHERE workspace_id=? ORDER BY id').all(workspaceId) as any[]).map(r=>target(r.id)!); },
    listCurrent(workspaceId: string) { return (db.prepare('SELECT t.id FROM review_targets t JOIN memory_schedule_states s ON s.review_target_id=t.id WHERE t.workspace_id=? AND t.status IN (\'pending_initial_review\',\'active\') ORDER BY s.due_at,t.id').all(workspaceId) as any[]).map(r=>({target:target(r.id)!,state:state(r.id)!})); },
    upsertTarget(t: ReviewTarget) { const x=ReviewTargetSchema.parse(t); db.prepare(`INSERT INTO review_targets(id,workspace_id,course_id,target_kind,origin_evidence_id,status,current_binding_version,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET status=excluded.status,current_binding_version=excluded.current_binding_version,updated_at=excluded.updated_at`).run(x.id,x.workspaceId,x.courseId,x.targetKind,x.originEvidenceId,x.status,x.currentBindingVersion,x.createdAt,x.updatedAt); return target(x.id)!; },
    getBinding: binding,
    insertBinding(b: ReviewTargetBinding) { const x=ReviewTargetBindingSchema.parse(b); db.prepare('INSERT INTO review_target_bindings(review_target_id,binding_version,contract_version_id,curriculum_version_id,learning_unit_id,objective_id,execution_source_manifest_fingerprint,valid_from,valid_to,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)').run(x.reviewTargetId,x.bindingVersion,x.contractVersionId,x.curriculumVersionId,x.learningUnitId,x.objectiveId,x.executionSourceManifestFingerprint,x.validFrom,x.validTo,x.createdAt); return binding(x.reviewTargetId,x.bindingVersion)!; },
    getState: state,
    insertPendingState(targetId:string, policyVersion:string, dueAt:string, at:string) { db.prepare('INSERT OR IGNORE INTO memory_schedule_states(review_target_id,policy_version,lifecycle_state,due_at,last_reviewed_at,stability,difficulty,scheduled_days,repetitions,lapses,last_review_event_id,row_version,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(targetId,policyVersion,'new',dueAt,null,0,1,0,0,0,null,1,at,at); return state(targetId)!; },
    saveState(s: MemoryScheduleState, expectedRowVersion: number) { const x=MemoryScheduleStateSchema.parse(s); const info=db.prepare(`UPDATE memory_schedule_states SET lifecycle_state=?,due_at=?,last_reviewed_at=?,stability=?,difficulty=?,scheduled_days=?,repetitions=?,lapses=?,last_review_event_id=?,row_version=?,updated_at=? WHERE review_target_id=? AND row_version=?`).run(x.lifecycleState,x.dueAt,x.lastReviewedAt,x.stability,x.difficulty,x.scheduledDays,x.repetitions,x.lapses,x.lastReviewEventId,x.rowVersion,x.updatedAt,x.reviewTargetId,expectedRowVersion); if(info.changes!==1) throw new Error('Review schedule state version conflict.'); return state(x.reviewTargetId)!; },
    findEventBySource(targetId:string, sourceOutcomeId:string, policyVersion:string) { const r=db.prepare('SELECT id FROM successor_review_events WHERE review_target_id=? AND source_outcome_id=? AND policy_version=?').get(targetId,sourceOutcomeId,policyVersion) as any; return r ? event(r.id) : undefined; },
    insertEvent(e: SuccessorReviewEvent) { const x=ReviewEventSchemaV2.parse(e); db.prepare('INSERT INTO successor_review_events(id,review_target_id,binding_version,policy_version,kind,source_outcome_id,review_execution_id,rating,occurred_at,recorded_at,pre_state,post_state,exact_input_time,due_at,idempotency_key) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(x.id,x.reviewTargetId,x.bindingVersion,x.policyVersion,x.kind,x.sourceOutcomeId,x.reviewExecutionId,x.rating,x.occurredAt,x.recordedAt,json(x.preState),json(x.postState),x.exactInputTime,x.dueAt,x.idempotencyKey); return event(x.id)!; },
    listEvents(targetId:string) { return (db.prepare('SELECT id FROM successor_review_events WHERE review_target_id=? ORDER BY occurred_at,id').all(targetId) as any[]).map(r=>event(r.id)!); },
    getExecution: execution,
    activeExecution(targetId:string) { const r=db.prepare("SELECT id FROM review_executions WHERE review_target_id=? AND status='active'").get(targetId) as any; return r ? execution(r.id) : undefined; },
    insertExecution(e: ReviewExecution) { const x=ReviewExecutionSchema.parse(e); db.prepare('INSERT INTO review_executions(id,review_target_id,binding_version,consumed_row_version,workspace_id,course_id,agenda_id,assessment_version_id,attempt_id,status,failure_reason,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)').run(x.id,x.reviewTargetId,x.bindingVersion,x.consumedRowVersion,x.workspaceId,x.courseId,x.agendaId,x.assessmentVersionId,x.attemptId,x.status,x.failureReason,x.createdAt,x.updatedAt); return execution(x.id)!; },
    updateExecution(e: ReviewExecution) { const x=ReviewExecutionSchema.parse(e); db.prepare('UPDATE review_executions SET assessment_version_id=?,attempt_id=?,status=?,failure_reason=?,updated_at=? WHERE id=?').run(x.assessmentVersionId,x.attemptId,x.status,x.failureReason,x.updatedAt,x.id); return execution(x.id)!; },
    commitEventAndState(e: SuccessorReviewEvent, s: MemoryScheduleState, expectedRowVersion: number) {
      const x = ReviewEventSchemaV2.parse(e);
      const next = MemoryScheduleStateSchema.parse(s);
      return db.transaction(() => {
        db.prepare('INSERT INTO successor_review_events(id,review_target_id,binding_version,policy_version,kind,source_outcome_id,review_execution_id,rating,occurred_at,recorded_at,pre_state,post_state,exact_input_time,due_at,idempotency_key) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(x.id,x.reviewTargetId,x.bindingVersion,x.policyVersion,x.kind,x.sourceOutcomeId,x.reviewExecutionId,x.rating,x.occurredAt,x.recordedAt,json(x.preState),json(x.postState),x.exactInputTime,x.dueAt,x.idempotencyKey);
        const info = db.prepare('UPDATE memory_schedule_states SET lifecycle_state=?,due_at=?,last_reviewed_at=?,stability=?,difficulty=?,scheduled_days=?,repetitions=?,lapses=?,last_review_event_id=?,row_version=?,updated_at=? WHERE review_target_id=? AND row_version=?').run(next.lifecycleState,next.dueAt,next.lastReviewedAt,next.stability,next.difficulty,next.scheduledDays,next.repetitions,next.lapses,next.lastReviewEventId,next.rowVersion,next.updatedAt,next.reviewTargetId,expectedRowVersion);
        if (info.changes !== 1) throw new Error('Review schedule state version conflict.');
        return { event: event(x.id)!, state: state(next.reviewTargetId)! };
      })();
    },
  };
}
export type ReviewSuccessorRepo = ReturnType<typeof createReviewSuccessorRepo>;
