import { newId, type Clock } from '../util/ids.js';
import type { Repositories } from '../repositories/index.js';
import { DEFAULT_CONFIGURATION, scheduleWithFsrs, type AdapterOutcome } from '../review/fsrsAdapter.js';
import { ReviewTargetSchema, type ReviewTarget, type ReviewTargetBinding, type MemoryScheduleState, type SuccessorReviewEvent } from '@hy3-clinic/shared';
export function createReviewSuccessorService({ repos, clock }: { repos: Repositories; clock: Clock }) {
  repos.reviewSuccessor.ensureConfiguration(DEFAULT_CONFIGURATION);
  function ensureTarget(input: { workspaceId:string; courseId:string; learningUnitId:string; objectiveId:string; contractVersionId:string; curriculumVersionId:string; manifestFingerprint:string; evidenceId?:string|null; at?:string; }): { target:ReviewTarget; binding:ReviewTargetBinding; state:MemoryScheduleState } {
    const at=input.at ?? clock.now().toISOString(); const id=`review-target:${input.workspaceId}:${input.objectiveId}`; let target=repos.reviewSuccessor.getTarget(id);
    if (!target) { target=ReviewTargetSchema.parse({id,workspaceId:input.workspaceId,courseId:input.courseId,targetKind:'curriculum_objective',originEvidenceId:input.evidenceId??null,status:'pending_initial_review',currentBindingVersion:1,createdAt:at,updatedAt:at}); repos.reviewSuccessor.upsertTarget(target); repos.reviewSuccessor.insertBinding({reviewTargetId:id,bindingVersion:1,contractVersionId:input.contractVersionId,curriculumVersionId:input.curriculumVersionId,learningUnitId:input.learningUnitId,objectiveId:input.objectiveId,executionSourceManifestFingerprint:input.manifestFingerprint,validFrom:at,validTo:null,createdAt:at}); repos.reviewSuccessor.insertPendingState(id,DEFAULT_CONFIGURATION.version,at,at); }
    const binding=repos.reviewSuccessor.getBinding(id,target.currentBindingVersion ?? 1); const state=repos.reviewSuccessor.getState(id); if(!binding||!state) throw new Error('Review target is missing its binding/state.');
    if(binding.contractVersionId!==input.contractVersionId||binding.curriculumVersionId!==input.curriculumVersionId||binding.learningUnitId!==input.learningUnitId||binding.objectiveId!==input.objectiveId||binding.executionSourceManifestFingerprint!==input.manifestFingerprint) throw new Error('Review target binding is stale or ambiguous.');
    return {target,binding,state};
  }
  function apply(input:{target:ReviewTarget; binding:ReviewTargetBinding; state:MemoryScheduleState; outcome:AdapterOutcome; kind:'activation'|'retrieval_failure'|'fresh_verification_success'; sourceOutcomeId:string; reviewExecutionId?:string|null; occurredAt?:string; }): SuccessorReviewEvent {
    const at=input.occurredAt ?? clock.now().toISOString(); const existing=repos.reviewSuccessor.findEventBySource(input.target.id,input.sourceOutcomeId,DEFAULT_CONFIGURATION.version); if(existing) return existing;
    if(input.kind==='fresh_verification_success' && input.reviewExecutionId && !repos.reviewSuccessor.listEvents(input.target.id).some(event => event.reviewExecutionId === input.reviewExecutionId && event.kind === 'retrieval_failure')) throw new Error('Initial Again event must be reconciled before Good.');
    const result=scheduleWithFsrs({state:input.state.dueAt===at && input.state.lifecycleState==='new' ? null : input.state,outcome:input.outcome,reviewTime:new Date(at),configuration:DEFAULT_CONFIGURATION});
    const eventId=newId('review_event'); const post={...result.state}; const event:SuccessorReviewEvent={id:eventId,reviewTargetId:input.target.id,bindingVersion:input.binding.bindingVersion,policyVersion:DEFAULT_CONFIGURATION.version,kind:input.kind,sourceOutcomeId:input.sourceOutcomeId,reviewExecutionId:input.reviewExecutionId??null,rating:input.outcome,occurredAt:at,recordedAt:clock.now().toISOString(),preState:input.state,postState:post,exactInputTime:at,dueAt:result.state.dueAt,idempotencyKey:`${input.target.id}:${input.sourceOutcomeId}:${DEFAULT_CONFIGURATION.version}`};
    const committed = repos.reviewSuccessor.commitEventAndState(event, { ...input.state,...result.state,lastReviewEventId:eventId,policyVersion:DEFAULT_CONFIGURATION.version,rowVersion:input.state.rowVersion+1,createdAt:input.state.createdAt,updatedAt:at }, input.state.rowVersion);
    repos.reviewSuccessor.upsertTarget({...input.target,status:'active',updatedAt:at}); return committed.event;
  }
  return {
    ensureTarget,
    activate(input: Parameters<typeof ensureTarget>[0] & { sourceOutcomeId:string; eligible:boolean; }) { if(!input.eligible) return null; const x=ensureTarget(input); if(x.target.status==='active') return null; return apply({ ...x,outcome:'Good',kind:'activation',sourceOutcomeId:input.sourceOutcomeId }); },
    successForActive(input: { targetId:string; sourceOutcomeId:string; executionId?:string|null }) { if (!input.executionId) throw new Error('ReviewExecution is required for Good.'); return this.recordFreshSuccess({ targetId: input.targetId, sourceOutcomeId: input.sourceOutcomeId, executionId: input.executionId }); },
    beginExecution(input:{targetId:string; workspaceId:string; courseId:string; agendaId?:string|null;}) { const target=repos.reviewSuccessor.getTarget(input.targetId); if(!target||target.workspaceId!==input.workspaceId||target.courseId!==input.courseId) throw new Error('Review target context is stale.'); const binding=repos.reviewSuccessor.getBinding(target.id,target.currentBindingVersion!); const state=repos.reviewSuccessor.getState(target.id); if(!binding||!state||target.status!=='active') throw new Error('Review target is not active.'); const active=repos.reviewSuccessor.activeExecution(target.id); if(active) return active; const now=clock.now().toISOString(); return repos.reviewSuccessor.insertExecution({id:newId('review_execution'),reviewTargetId:target.id,bindingVersion:binding.bindingVersion,consumedRowVersion:state.rowVersion,workspaceId:input.workspaceId,courseId:input.courseId,agendaId:input.agendaId??null,assessmentVersionId:null,attemptId:null,status:'active',failureReason:null,createdAt:now,updatedAt:now}); },
    completeExecution(input:{executionId:string; assessmentVersionId?:string|null; attemptId?:string|null;}) { const execution=repos.reviewSuccessor.getExecution(input.executionId); if(!execution||execution.status!=='active') throw new Error('Review execution is not active.'); return repos.reviewSuccessor.updateExecution({...execution,assessmentVersionId:input.assessmentVersionId??execution.assessmentVersionId,attemptId:input.attemptId??execution.attemptId,status:'completed',updatedAt:clock.now().toISOString()}); },
    recordDueFailure(input:{targetId:string; sourceOutcomeId:string; executionId:string;}) { const execution=repos.reviewSuccessor.getExecution(input.executionId); if(!execution||execution.status!=='active'||execution.reviewTargetId!==input.targetId) throw new Error('Review execution is stale or inactive.'); const target=repos.reviewSuccessor.getTarget(input.targetId); if(!target) throw new Error('Review target not found.'); const binding=repos.reviewSuccessor.getBinding(target.id,target.currentBindingVersion!); const state=repos.reviewSuccessor.getState(target.id); if(!binding||!state||state.rowVersion!==execution.consumedRowVersion) throw new Error('Review execution row version is stale.'); return apply({target,binding,state,outcome:'Again',kind:'retrieval_failure',sourceOutcomeId:input.sourceOutcomeId,reviewExecutionId:input.executionId}); },
    recordFreshSuccess(input:{targetId:string; sourceOutcomeId:string; executionId:string;}) { const execution=repos.reviewSuccessor.getExecution(input.executionId); if(!execution||execution.status!=='active'||execution.reviewTargetId!==input.targetId) throw new Error('Review execution is stale or inactive.'); const target=repos.reviewSuccessor.getTarget(input.targetId); if(!target) throw new Error('Review target not found.'); const binding=repos.reviewSuccessor.getBinding(target.id,target.currentBindingVersion!); const state=repos.reviewSuccessor.getState(target.id); if(!binding||!state||state.rowVersion!==execution.consumedRowVersion) throw new Error('Review execution row version is stale.'); const event=apply({target,binding,state,outcome:'Good',kind:'fresh_verification_success',sourceOutcomeId:input.sourceOutcomeId,reviewExecutionId:input.executionId}); repos.reviewSuccessor.updateExecution({...execution,status:'completed',updatedAt:clock.now().toISOString()}); return event; },
    listDue(workspaceId:string, at=clock.now()) { return repos.reviewSuccessor.listTargets(workspaceId).map(target=>({target,state:repos.reviewSuccessor.getState(target.id),binding:repos.reviewSuccessor.getBinding(target.id,target.currentBindingVersion!)})).filter(x=>x.target.status==='active'&&x.state&&new Date(x.state.dueAt).getTime()<=at.getTime()).sort((a,b)=>new Date(a.state!.dueAt).getTime()-new Date(b.state!.dueAt).getTime()||a.target.id.localeCompare(b.target.id)); },
    getTarget: repos.reviewSuccessor.getTarget,
    listCurrent(workspaceId:string) { return repos.reviewSuccessor.listCurrent(workspaceId).map(({target,state})=>({target,state,binding:repos.reviewSuccessor.getBinding(target.id,target.currentBindingVersion!)})).filter(x=>x.binding); },
  };
}
export type ReviewSuccessorService = ReturnType<typeof createReviewSuccessorService>;
